apiVersion: v1
kind: Service
metadata:
  name: {{ include "nodepartition.fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nodepartition.controller.labels" . | nindent 4 }}
  annotations:
    {{- if eq .Values.controller.webhook.tls.mode "openshift" }}
    service.beta.openshift.io/serving-cert-secret-name: {{ include "nodepartition.fullname" . }}-webhook-tls
    {{- end }}
spec:
  ports:
    - port: 443
      targetPort: webhook
      protocol: TCP
      name: webhook
  selector:
    {{- include "nodepartition.controller.selectorLabels" . | nindent 4 }}
